add_data = "INSERT INTO expense (datetime, category, amount) VALUES (%s, %s, %s)"
get_data ="SELECT * FROM expense"
delete ="DELETE FROM expense WHERE expense_id = %s"
update ="Update expense SET datetime= %s,category= %s,amount= %s where expense_id = %s"
m_query = "Select Date_Format(datetime ,'%Y-%m') as Month ,sum(amount) as Monthly_spending from expense Group By Month Order By Month"
h_query = "Select * from expense where amount = (Select max(amount) from expense)"
c_query ="Select category,sum(amount) as Total_Amount from expense group by category"
a_query ="Select avg(amount) from expense"
t_query ="Select Sum(amount) As Total_Amount from expense"
